[colors.bright]
black = "#555753"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#E19FE7"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#808080"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#C388D1"
red = "#ef2929"
white = "#d3d7cf"
yellow = "#fce94f"

[colors.primary]
background = "#000000"
foreground = "#e3e3ea"

[colors.selection]
background = "#ff7f7f"
text = "#FFFFFF"

[window]
opacity = 0.73

[font]
# normal = { family = "FiraMono Nerd font", style = "Bold" }
# bold = { family = "FiraMono Nerd font", style = "Bold" }
# italic = { family = "FiraMono Nerd font", style = "Italic" }
# bold_italic = { family = "FiraMono Nerd font", style = "Bold Italic" }

# Hack Nerd Font configuration
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
normal = { family = "JetBrains Mono Nerd Font", style = "bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "italic" }
bold_italic = { family = "hack nerd font", style = "bold italic" }

# size = 9.5
size = 10.3
