[colors.bright]
black = "#555753"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#E19FE7"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#808080"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#C388D1"
red = "#ef2929"
white = "#d3d7cf"
yellow = "#fce94f"

[colors.primary]
background = "#000000"
foreground = "#e3e3ea"

[colors.selection]
background = "#ff7f7f"
text = "#FFFFFF"

[window]
opacity = 0.75

[font]
normal = { family = "Source Code Pro", style = "Bold" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }

# normal = { family = "FiraMono Nerd font", style = "Bold" }
# bold = { family = "FiraMono Nerd font", style = "Bold" }
# italic = { family = "FiraMono Nerd font", style = "Italic" }
# bold_italic = { family = "FiraMono Nerd font", style = "Bold Italic" }
size = 7.5 # You can adjust the size according to your preference
